### ISSUE TITLE
我是傻逼

### ISSUE THREAD

**Issue by zqm64** [ililaoban/android_device_samsung_j3109#1]
你说，
你之前和炕研究的FRP为什么最终被你私吞了
为什么崇拜你你就不管，不崇拜就不服退群

**我也懒得和你说那么多，到时候看结果**

**Comment by zqm64** [comment]
#我也懒得和你说那么多，到时候看结果#

**Comment by ililaoban** [comment]
私吞?私吞我还为什么还要到b站发视频，我为什么还到机锋发教程，贴吧也发，虽然被狗85删了

**Comment by ililaoban** [comment]
说别的没用，就问你一个问题 你想让我怎么? 我尽量满足你

**Comment by zqm64** [comment]
别再搞/纵容个人崇拜/资本/教条主义

**Comment by zqm64** [comment]
不崇拜你就退群

**Comment by zqm64** [comment]
还不是你在纵容？

**Comment by zqm64** [comment]
反正我就要民主 共和

**Comment by ililaoban** [comment]
我退不退群那是我的事，按政治术语叫内政，别国无权干涉。再说了J群我已经彻底丧失希望了，我回去，也起不到什么积极作用

**Comment by ililaoban** [comment]
你要民主共和你就自己去搞啊，杀出一条血路来，群都给你了，你想怎么搞就怎么搞啊

**Comment by zqm64** [comment]
我到时候倒是想看看，你到时候用我们合作做的Android 8.0还是不服换手机

**Comment by zqm64** [comment]
等着我们打倒懒科生专制吧，再见

**Comment by ililaoban** [comment]
那你看吧
